language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - travis_retry pip install -e .
  - travis_retry pip install coverage coveralls

script: py.test --cov flask_jsonschema_ext --cov-report term-missing

after_script:
  - coveralls

branches:
  only:
    - master
